version: '3.9'

services:
  flask:
    command: bash -c 'flask db init && flask db migrate -m "aval" &&  flask db upgrade && python app.py'
    restart: always
    build: .
    image: blog:v3
      #volumes:
      # - ./flask-app:/app
    ports:
      - 5000:5000

    environment:
      - DB_URL=postgresql://postgres:postgres@postgres_db:5432/postgres


    tty: true
    networks:
      - asgard
    depends_on:
      - postgres_db 

  postgres_db:
    container_name: postgres_db
    restart: always
    image: postgres:13
    ports:
      - 5432:5432

    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres

    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - asgard

networks:
  asgard:
    driver: bridge  
